### ISSUE TITLE
bbc radio stream

### ISSUE THREAD

**Issue by voyeg3r** [voyeg3r/dotfiles#50]
http://peace.str3am.com:6810/live-96k.mp3.m3u

**Comment by voyeg3r** [comment]
alias radio_dogmazic='mplayer -nocache -afm acm http://radio.dogmazic.net:8000/radio_dogmazic.ogg'
    alias radio_oxyradio='mplayer -nocache -afm acm http://www.oxyradio.net/listen/80.pls'
    alias radio_classique='mplayer -nocache -afm acm http://str2.creacast.com:86/listen.pls'
    alias radio_radiometal='mplayer -nocache -afm acm http://www.radiometal.fr/rm.m3u'
    alias radio_radionova='mplayer -nocache -afm acm http://broadcast.infomaniak.net/radionova-high.mp3'

**Comment by emanoelopes** [comment]
The link is bronken

**Comment by emanoelopes** [comment]
Sorry, I tried to open on chrome directly!
